function pFR = visualize(in1,in2)
%VISUALIZE
%    PFR = VISUALIZE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    29-Jan-2019 21:30:49

L1 = in2(:,1);
L2 = in2(:,2);
L3 = in2(:,3);
LCenter = in2(:,4);
qR1 = in1(:,1);
qR2 = in1(:,2);
qR3 = in1(:,3);
t2 = cos(qR1);
t3 = L1.*t2;
t4 = qR1+qR2;
t5 = cos(t4);
t6 = L2.*t5;
t7 = sin(qR1);
t8 = L1.*t7;
t9 = sin(t4);
t10 = L2.*t9;
t11 = qR1+qR2+qR3;
pFR = reshape([LCenter,0.0,LCenter+t3,t8,LCenter+t3+t6,t8+t10,LCenter+t3+t6+L3.*cos(t11),t8+t10+L3.*sin(t11)],[2,4]);
